// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDokcfPVaU3pTmrl29XsZA_0xlFq8yWmos',
    appId: '1:651176487313:web:0dd25954c48befa23ad230',
    messagingSenderId: '651176487313',
    projectId: 'quiz-1203c',
    authDomain: 'quiz-1203c.firebaseapp.com',
    storageBucket: 'quiz-1203c.appspot.com',
    measurementId: 'G-339F4344S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0y4BlEm-N8ZDGHKwVFtJnJqjIskRYafU',
    appId: '1:651176487313:android:1db88c01ae6f65c83ad230',
    messagingSenderId: '651176487313',
    projectId: 'quiz-1203c',
    storageBucket: 'quiz-1203c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw6Do1b2gee02dDanqE9pcbEF4C3kVH_Y',
    appId: '1:651176487313:ios:cbbb66e4e248934c3ad230',
    messagingSenderId: '651176487313',
    projectId: 'quiz-1203c',
    storageBucket: 'quiz-1203c.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw6Do1b2gee02dDanqE9pcbEF4C3kVH_Y',
    appId: '1:651176487313:ios:cbbb66e4e248934c3ad230',
    messagingSenderId: '651176487313',
    projectId: 'quiz-1203c',
    storageBucket: 'quiz-1203c.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDokcfPVaU3pTmrl29XsZA_0xlFq8yWmos',
    appId: '1:651176487313:web:92d1495fa3f619a53ad230',
    messagingSenderId: '651176487313',
    projectId: 'quiz-1203c',
    authDomain: 'quiz-1203c.firebaseapp.com',
    storageBucket: 'quiz-1203c.appspot.com',
    measurementId: 'G-GTS6LL352K',
  );
}
